In [42]:
# Dependencies
import pandas as pd

In [43]:
# Read the data into a Pandas DataFrame
yelp_data = pd.read_csv('data/yelp_data.csv')
yelp_data.head()

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,transactions,...,coordinates.latitude,coordinates.longitude,location.address1,location.address2,location.address3,location.city,location.zip_code,location.country,location.state,location.display_address
0,5ErYddAotaR4swc37qc87g,lot-twenty-perth,Lot Twenty,https://s3-media1.fl.yelpcdn.com/bphoto/t-Crn8...,False,https://www.yelp.com/biz/lot-twenty-perth?adju...,85,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",4.2,[],...,-31.949332,115.859543,206/198-206 William St,NaN,NaN,Perth,6000,AU,WA,"['206/198-206 William St', 'Perth Western Aust..."
1,30UX2wFjo_jK82LQVbW1-g,angel-falls-grill-perth,Angel Falls Grill,https://s3-media1.fl.yelpcdn.com/bphoto/_NCdZw...,False,https://www.yelp.com/biz/angel-falls-grill-per...,35,"[{'alias': 'latin', 'title': 'Latin American'}...",4.3,[],...,-31.951890,115.853620,Shop 16,Shafto Lane,NaN,Perth,6000,AU,WA,"['Shop 16', 'Shafto Lane', 'Perth Western Aust..."
2,cKutCnn0zwh2ckB91qXffw,santini-bar-and-grill-perth,Santini Bar & Grill,https://s3-media1.fl.yelpcdn.com/bphoto/gYQYcn...,False,https://www.yelp.com/biz/santini-bar-and-grill...,8,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.9,[],...,-31.953870,115.861000,133 Murray Street,NaN,QT Hotel,Perth,6000,AU,WA,"['133 Murray Street', 'QT Hotel', 'Perth Weste..."
3,dhRlSOvJKRixjchNBlxUQw,the-standard-northbridge-2,The Standard,https://s3-media2.fl.yelpcdn.com/bphoto/Rk8goQ...,False,https://www.yelp.com/biz/the-standard-northbri...,75,"[{'alias': 'tapasmallplates', 'title': 'Tapas/...",4.4,[],...,-31.949290,115.857880,28 Roe St,NaN,NaN,Northbridge,6003,AU,WA,"['28 Roe St', 'Northbridge Western Australia 6..."
4,58s8W4qQdhQv7RtlSb9cvA,hao-szechuan-northbridge,Hao Szechuan,https://s3-media2.fl.yelpcdn.com/bphoto/FQklmY...,False,https://www.yelp.com/biz/hao-szechuan-northbri...,1,"[{'alias': 'szechuan', 'title': 'Szechuan'}]",5.0,[],...,-31.947222,115.858364,74 Francis St,NaN,NaN,Northbridge,6003,AU,WA,"['74 Francis St', 'Northbridge Western Austral..."

In [44]:
# Get a brief summary of the yelp_data DataFrame.
yelp_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942 entries, 0 to 941
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        942 non-null    object
 1   alias                     942 non-null    object
 2   name                      942 non-null    object
 3   image_url                 885 non-null    object
 4   is_closed                 942 non-null    bool
 5   url                       942 non-null    object
 6   review_count              942 non-null    int64
 7   categories                942 non-null    object
 8   rating                    942 non-null    float64
 9   transactions              942 non-null    object
 10  price                     610 non-null    object
 11  phone                     808 non-null    float64
 12  display_phone             808 non-null    object
 13  distance                  942 non-null    float64
 14  coordinates.latitude      941 non-null    float64
 15  coordinates.longitude     941 non-null    float64
 16  location.address1         936 non-null    object
 17  location.address2         287 non-null    object
 18  location.address3         16 non-null     object
 19  location.city             942 non-null    object
 20  location.zip_code         935 non-null    object
 21  location.country          942 non-null    object
 22  location.state            942 non-null    object
 23  location.display_address  942 non-null    object
dtypes: bool(1), float64(5), int64(1), object(17)
memory usage: 170.3+ KB

In [48]:
# Create a new column 'id' with integer IDs starting from 0
yelp_data['id'] = range(len(yelp_data))

# Set the 'id' column as the index
yelp_data.set_index('id', inplace=True)

In [51]:
# Drop unwanted columns
columns_to_drop = ['alias', 'phone', 'is_closed','transactions', 'location.address2', 'location.address3', 'location.zip_code', 'location.state', 'location.country' ]
yelp_data_1 = yelp_data.drop(columns_to_drop, axis = 1)
yelp_data_1.head()

,name,image_url,url,review_count,categories,rating,price,display_phone,distance,coordinates.latitude,coordinates.longitude,location.address1,location.city,location.display_address
id,,,,,,,,,,,,,,
0,Lot Twenty,https://s3-media1.fl.yelpcdn.com/bphoto/t-Crn8...,https://www.yelp.com/biz/lot-twenty-perth?adju...,85,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",4.2,$$,+61 8 6162 1195,46.382139,-31.949332,115.859543,206/198-206 William St,Perth,"['206/198-206 William St', 'Perth Western Aust..."
1,Angel Falls Grill,https://s3-media1.fl.yelpcdn.com/bphoto/_NCdZw...,https://www.yelp.com/biz/angel-falls-grill-per...,35,"[{'alias': 'latin', 'title': 'Latin American'}...",4.3,$$,+61 8 9481 6222,629.509791,-31.951890,115.853620,Shop 16,Perth,"['Shop 16', 'Shafto Lane', 'Perth Western Aust..."
2,Santini Bar & Grill,https://s3-media1.fl.yelpcdn.com/bphoto/gYQYcn...,https://www.yelp.com/biz/santini-bar-and-grill...,8,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.9,NaN,+61 8 9225 8000,568.453539,-31.953870,115.861000,133 Murray Street,Perth,"['133 Murray Street', 'QT Hotel', 'Perth Weste..."
3,The Standard,https://s3-media2.fl.yelpcdn.com/bphoto/Rk8goQ...,https://www.yelp.com/biz/the-standard-northbri...,75,"[{'alias': 'tapasmallplates', 'title': 'Tapas/...",4.4,$$,+61 8 9228 1331,148.760367,-31.949290,115.857880,28 Roe St,Northbridge,"['28 Roe St', 'Northbridge Western Australia 6..."
4,Hao Szechuan,https://s3-media2.fl.yelpcdn.com/bphoto/FQklmY...,https://www.yelp.com/biz/hao-szechuan-northbri...,1,"[{'alias': 'szechuan', 'title': 'Szechuan'}]",5.0,$$,+61 8 9228 0636,213.249966,-31.947222,115.858364,74 Francis St,Northbridge,"['74 Francis St', 'Northbridge Western Austral..."

In [55]:
# Drop rows with NaN values in any column
yelp_data_1.dropna(inplace=True)

In [56]:
yelp_data_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 530 entries, 0 to 940
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      530 non-null    object
 1   image_url                 530 non-null    object
 2   url                       530 non-null    object
 3   review_count              530 non-null    int64
 4   categories                530 non-null    object
 5   rating                    530 non-null    float64
 6   price                     530 non-null    object
 7   display_phone             530 non-null    object
 8   distance                  530 non-null    float64
 9   coordinates.latitude      530 non-null    float64
 10  coordinates.longitude     530 non-null    float64
 11  location.address1         530 non-null    object
 12  location.city             530 non-null    object
 13  location.display_address  530 non-null    object
dtypes: float64(4), int64(1), object(9)
memory usage: 62.1+ KB